### ISSUE TITLE
CSRF verification failure

### ISSUE THREAD

**Issue by Alir3z4** [jpadilla/django-jwt-auth#2]
Hi,

Shouldn't `jwt_auth.views.ObtainJSONWebToken` be exempt  from CSRF verification ? Mostly people go (or I at least ) for jwt solution to get rid of cookies authentication solution ?

If exempt CSRF is fine by the maintainer I'd be happy to submit a patch.

**Comment by iamkhush** [comment]
+1

**Comment by jpadilla** [comment]
Yeah makes sense

**Comment by Alir3z4** [comment]
@jpadilla @iamkhush Pull request #4 is there that fixes this issue.

@jpadilla Thanks for the great work on `pyjwt` and this `django-jwt-auth`.

**Comment by kalyanvgopal-zz** [comment]
Any plans to merge this change to master?

**Comment by jpadilla** [comment]
@kalyanvgopal haven't merged because tests are failing. If anyone wants to take that one and submit a new PR, I'll gladly take a look at it.

**Comment by jpadilla** [comment]
Closed by #5
